INFO 08-17 19:18:57 [__init__.py:235] Automatically detected platform cuda.
2025-08-17 19:18:59,524	WARNING node.py:1882 -- The object spilling config is specified from an unstable API - system config or environment variable. This is subject to change in the future. You can use the stable API - --object-spilling-directory in ray start or object_spilling_directory in ray.init() to specify the object spilling directory instead. If you need more advanced settings, please open a github issue with the Ray team.
Patching UnstableBaselines collector for OpenAI agent support...
Collector patched successfully!
Traceback (most recent call last):
  File "/home/aiscuser/mindgames/UnstableBaselines/example_a2c.py", line 64, in <module>
    ray.init(
  File "/home/aiscuser/miniconda3/envs/rl/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/aiscuser/miniconda3/envs/rl/lib/python3.10/site-packages/ray/_private/worker.py", line 1825, in init
    _global_node = ray._private.node.Node(
  File "/home/aiscuser/miniconda3/envs/rl/lib/python3.10/site-packages/ray/_private/node.py", line 259, in __init__
    self.validate_external_storage()
  File "/home/aiscuser/miniconda3/envs/rl/lib/python3.10/site-packages/ray/_private/node.py", line 1839, in validate_external_storage
    storage = external_storage.setup_external_storage(
  File "/home/aiscuser/miniconda3/envs/rl/lib/python3.10/site-packages/ray/_private/external_storage.py", line 584, in setup_external_storage
    _external_storage = FileSystemStorage(node_id, **config["params"])
KeyError: 'params'
